<a href="https://colab.research.google.com/github/AarkeTripathi/Python-Education/blob/master/TensorflowEd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import mnist

Initialization of Tensors

In [2]:
#passing constant numbers as a tensor
x=tf.constant(4)
print(x)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
#defining the shape(basically, dimension like it is to be treated as a constant, vector, matrix, 4d or any other dimensional, but only logically valid dimesnsion) and datatype of a tensor manually
x=tf.constant([[4]], shape=(1,1), dtype=tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [4]:
#some popular tensors
x=tf.ones((3,3))
print(x)
x=tf.zeros((2,3,2))
print(f'\n {x}')
x=tf.eye(3)           #identity matrix
print(f'\n {x}')

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)

 [[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#changing the data type
x=tf.cast(x, dtype=tf.float64)

Mathematical Operations

In [6]:
x=tf.constant([1,2,3])
y=tf.constant([2,3,4])
print(x+y)
#or
print(tf.add(x,y))

tf.Tensor([3 5 7], shape=(3,), dtype=int32)
tf.Tensor([3 5 7], shape=(3,), dtype=int32)


In [7]:
#dot product
print(tf.tensordot(x,y,axes=1))

tf.Tensor(20, shape=(), dtype=int32)


In [8]:
 #sum of all numbers in a tensor
 x=tf.constant([[6,3,4],[1,2,3]])
 z=tf.reduce_sum(x)
 print(z)

tf.Tensor(19, shape=(), dtype=int32)


Neural Networks

In [9]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [10]:
print(x_train.shape,'\n',y_train.shape)

(60000, 28, 28) 
 (60000,)


In [ ]:
x_train=x_train.reshape()